In [80]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

In [98]:
dataset = pd.read_csv('Features.csv')
x = dataset.iloc[:10, :-1].values
y = dataset.iloc[:10, -1].values

In [99]:
print(x)

[['0VjIjW4GlUZAMYd2vXMi3b' 'Blinding Lights' 3.33 0.73 1 -5.934 1 0.0598
  0.00146 9.54e-05 0.0897 0.334 171.005]
 ['7qiZfU4dY1lWllzX7mPBI3' 'Shape of You' 3.9 0.652 1 -3.183 0 0.0802
  0.581 0.0 0.0931 0.931 95.977]
 ['2XU0oxnq2qxCpomAAuJY8K' 'Dance Monkey' 3.49 0.588 6 -6.4 0 0.0924
  0.692 0.000104 0.149 0.513 98.027]
 ['7qEHsqek33rTcFNT9PFqLf' 'Someone You Loved' 3.04 0.405 1 -5.679 1
  0.0319 0.751 0.0 0.105 0.446 109.891]
 ['0e7ipj03S05BNilyu5bRzt' 'Rockstar' 3.64 0.52 5 -6.136 0 0.0712 0.124
  7.01e-05 0.131 0.129 159.801]
 ['3KkXRkHbMCARz0aVfEt68P' 'Sunflower' 2.63 0.479 2 -5.574 1 0.0466 0.556
  0.0 0.0703 0.913 89.911]
 ['1zi7xx7UVEFkmKfv06H8x0' 'One Dance' 2.9 0.625 1 -5.609 1 0.0536
  0.00776 0.0018 0.329 0.37 103.967]
 ['7BKLCZ1jbUBVqRi2FVlTVw' 'Closer' 4.08 0.524 8 -5.599 1 0.0338 0.414
  0.0 0.111 0.661 95.01]
 ['789CxjEOtO76BVD1A9yJQH' 'Stay' 4.01 0.31 9 -10.164 0 0.0283 0.945
  6.12e-05 0.117 0.125 111.893]
 ['0pqnGHJpmpxLKifKRmU6WP' 'Believer' 3.41 0.78 10 -4.374 0 0.

In [100]:
print(y)

[0.514 0.825 0.824 0.501 0.585 0.76  0.792 0.748 0.621 0.776]


In [101]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 2:4])
x[:, 2:4] = imputer.transform(x[:, 2:4])

In [102]:
print(x)

[['0VjIjW4GlUZAMYd2vXMi3b' 'Blinding Lights' 3.33 0.73 1 -5.934 1 0.0598
  0.00146 9.54e-05 0.0897 0.334 171.005]
 ['7qiZfU4dY1lWllzX7mPBI3' 'Shape of You' 3.9 0.652 1 -3.183 0 0.0802
  0.581 0.0 0.0931 0.931 95.977]
 ['2XU0oxnq2qxCpomAAuJY8K' 'Dance Monkey' 3.49 0.588 6 -6.4 0 0.0924
  0.692 0.000104 0.149 0.513 98.027]
 ['7qEHsqek33rTcFNT9PFqLf' 'Someone You Loved' 3.04 0.405 1 -5.679 1
  0.0319 0.751 0.0 0.105 0.446 109.891]
 ['0e7ipj03S05BNilyu5bRzt' 'Rockstar' 3.64 0.52 5 -6.136 0 0.0712 0.124
  7.01e-05 0.131 0.129 159.801]
 ['3KkXRkHbMCARz0aVfEt68P' 'Sunflower' 2.63 0.479 2 -5.574 1 0.0466 0.556
  0.0 0.0703 0.913 89.911]
 ['1zi7xx7UVEFkmKfv06H8x0' 'One Dance' 2.9 0.625 1 -5.609 1 0.0536
  0.00776 0.0018 0.329 0.37 103.967]
 ['7BKLCZ1jbUBVqRi2FVlTVw' 'Closer' 4.08 0.524 8 -5.599 1 0.0338 0.414
  0.0 0.111 0.661 95.01]
 ['789CxjEOtO76BVD1A9yJQH' 'Stay' 4.01 0.31 9 -10.164 0 0.0283 0.945
  6.12e-05 0.117 0.125 111.893]
 ['0pqnGHJpmpxLKifKRmU6WP' 'Believer' 3.41 0.78 10 -4.374 0 0.

In [103]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [104]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 3.33 0.73 1 -5.934 1 0.0598 0.00146 9.54e-05 0.0897 0.334
  171.005]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 3.9 0.652 1 -3.183 0 0.0802 0.581 0.0 0.0931 0.931 95.977]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 3.49 0.588 6 -6.4 0 0.0924 0.692 0.000104 0.149 0.513 98.027]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  0.0 0.0 3.04 0.405 1 -5.679 1 0.0319 0.751 0.0 0.105 0.446 109.891]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 3.64 0.52 5 -6.136 0 0.0712 0.124 7.01e-05 0.131 0.129 159.801]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 1.0 2.63 0.479 2 -5.574 1 0.0466 0.556 0.0 0.0703 0.913 89.911]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 2.9 0.625 1 -5.609 1 0.0536 0.00776 0.

In [105]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [106]:
print(y)

[1 9 8 0 2 5 7 4 3 6]


In [107]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [108]:
print(x_train)


[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0
  0.0 0.0 2.9 0.625 1 -5.609 1 0.0536 0.00776 0.0018 0.329 0.37 103.967]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0
  0.0 0.0 3.64 0.52 5 -6.136 0 0.0712 0.124 7.01e-05 0.131 0.129 159.801]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 3.33 0.73 1 -5.934 1 0.0598 0.00146 9.54e-05 0.0897 0.334
  171.005]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0
  0.0 0.0 3.04 0.405 1 -5.679 1 0.0319 0.751 0.0 0.105 0.446 109.891]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0
  0.0 0.0 3.9 0.652 1 -3.183 0 0.0802 0.581 0.0 0.0931 0.931 95.977]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 4.08 0.524 8 -5.599 1 0.0338 0.414 0.0 0.111 0.661 95.01]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  1.0 0.0 4.01 0.31 9 -10.164 0 0.0283 0.945 6.12

In [109]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0
  0.0 0.0 3.49 0.588 6 -6.4 0 0.0924 0.692 0.000104 0.149 0.513 98.027]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
  0.0 0.0 3.41 0.78 10 -4.374 0 0.128 0.0622 0.0 0.081 0.666 124.949]]


In [110]:
print(y_train)

[7 2 1 0 9 4 3 5]


In [111]:
print(y_test)

[8 6]


In [112]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [113]:
print(x_train)

[[0.0 0.0 0.0 2.6457513110645903 0.0 -0.3779644730092272
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 0.0 -0.3779644730092272 -0.3779644730092272 0.0
  2.6457513110645903 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -1.0549340724785072 0.7384439622828901 -0.7905694150420948
  0.20885648795467213 0.7745966692414834 0.16417645148967536
  -1.263325084648297 2.640724260961565 2.578044543243598
  -0.399076722981044 -0.4582115193902722]
 [0.0 1.0 0.0 -0.3779644730092272 0.0 -0.3779644730092272
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 0.0 -0.3779644730092272 -0.3779644730092272 0.0
  -0.3779644730092272 2.6457513110645903 -0.3779644730092272
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  0.3873776386237484 -0.08313607522390151 0.4743416490252569
  -0.08407064219066981 -1.2909944487358056 1.1520415954959256
  -0.9092739407194259 -0.312854

In [114]:
print(x_test)

[[0.0 0.0 0.0 -0.3779644730092272 1.0 -0.3779644730092272
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 0.0 -0.3779644730092272 -0.3779644730092272 1.0
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  0.09501715664356174 0.44893480620906795 0.7905694150420948
  -0.23081212674165713 -1.2909944487358056 2.341970064412545
  0.8207763840534471 -0.2549742812807239 0.23717554628869458
  0.08200206636596809 -0.6641746045634742]
 [0.0 0.0 1.0 -0.3779644730092272 0.0 -0.3779644730092272
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 1.0 -0.3779644730092272 -0.3779644730092272 0.0
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.0609084337458714 1.9512525890786305 2.0554804791094465
  0.8953175993958434 -1.2909944487358056 4.340151832970643
  -1.0975082894359112 -0.43